#!/bin/sh

#
# Installation script for schema product
#

cd `dirname $0`

#
# Create symbolic links.
#
#for i in table key index view trigger
for i in table key index view
do
    cd $i
    rm -rf Configuration logs
    ln -s ../Configuration .
    ln -s ../logs/$i logs
    cd ..
done

